services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
      args:
        VITE_SPOTIFY_CLIENT_ID: ${VITE_SPOTIFY_CLIENT_ID}
    ports:
      - "80:80"
    container_name: melo-react-app
    image: react-app:1.0
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
